### ISSUE TITLE
Missing Order Info

### ISSUE THREAD

**Issue by neopaws** [NKoonen/Personal-Salesmen#1]
Hello,

I have an issue with viewing order infos such as Customer Address & shipping info.

Instance:
Link Customer1 to Employee1
Employee1 creates an order for Customer1
Employee1 goes to view the order and does NOT see the shipping tab and Customer Info such as address/email etc..

I am running Prestashop 1.6.1.7

Personal Salesmen is uninstalled:
![nopersonalsalesmen](https://cloud.githubusercontent.com/assets/7387394/19118372/34f94b42-8aea-11e6-9142-1f9255b9c73d.jpg) 

Personal Salesmen is installed (viewing the same order):
![personalsalesmen](https://cloud.githubusercontent.com/assets/7387394/19118384/38a3f3be-8aea-11e6-9ebc-39c140f20333.jpg)

**Comment by NKoonen** [comment]
Yes, that is correct. Thank you for pointing this out. In my case particular i needed this. Will make a bunch of options in the module to disable this.

**Comment by NKoonen** [comment]
Dont have time to actually test it, but i've bug fixed it. In the override i edited 2 files. 
Update those 2 files, en delete your cache/class_index.php  and then it should be fine.
Let me know if it works!

**Comment by neopaws** [comment]
I edited my:
www/modules/personalsalesmen/override/controllers/admin/AdminCustomersController.php
www/modules/personalsalesmen/override/controllers/admin/AdminOrdersController.php

As well as:
www/override/controllers/admin/AdminCustomersController.php
www/override/controllers/admin/AdminOrdersController.php

I deleted my www/cache/class_index.php
In backoffice, i went to Advanced Paraments - Performance and "Clear cache"

I created a new order and i still do not see the shipping box after an order has been created :(

**Comment by NKoonen** [comment]
I see I see. Working on it!

**Comment by NKoonen** [comment]
Fixed. You can now configure the module to show or hide the extra options for Personal Salesmen.

**Comment by neopaws** [comment]
Thank you !! Looks good now!

Keep up the good work!
