### ISSUE TITLE
Missing Customers and Orders

### ISSUE THREAD

**Issue by marschallphilipp** [NKoonen/Personal-Salesmen#2]
Hi there,
I installed the module and now all customers and Orders are not visible anymore....
I couldnt choose any customer or employee in the configuration, dropdown was empty.

They seem to be in the database still, but when I want to list the orders it shows zero entries...
When I got to Adresses and pick an adress I am redirected to the customer of this adress correctly.
When I uninstalled the module everything was fine again.
Using Prestashop version: 1.6.0.6

**Comment by NKoonen** [comment]
Sorry my late response! 
The thing is, only the SUPER ADMIN with ID #1 can see all the customers.

**Comment by reanim8ed** [comment]
Is there a solution that all Superadmins could see all customers?

**Comment by NKoonen** [comment]
Thanks for the good and easy solution i've been searching for. I've changed it that SuperAdmin's can now see everything. This means you can now choose what employee's can see everything.

**Comment by reanim8ed** [comment]
Glad to help with idea :)
I have installed the updated version, but it still works the same.

**Comment by NKoonen** [comment]
Yep, fixed... my bad 👍
